# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.92.0
    hooks:
      - id: terraform_fmt
        args:
         - --args=--recursive
      - id: terraform_tflint
        args:
         - --args=--recursive
         - --args=--disable-rule terraform_required_version --disable-rule terraform_required_providers
      - id: terraform_validate
        args:
         - --hook-config=--retry-once-with-cleanup=true
         - --tf-init-args=--backend=false
  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.18.4
    hooks:
    - id: gitleaks
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
    - id: black
