name: "[CI] Deploy Terraform stacks"
on:
  pull_request:
    branches:
      - main

jobs:
  dev_deploy:
    name: Deploy Development Terraform
    uses: UKHSA-Internal/devops-github-reusable-workflows/.github/workflows/terraform-plan-apply.yml@main
    permissions:
      packages: read
      contents: read
      security-events: write
      statuses: write
      checks: write
      id-token: write
    with:
      environment_name: dev
    secrets:
      # AWS Secrets
      AWS_ACCESS_KEY_ID: "${{ secrets.AWS_ACCESS_KEY_ID }}"
      AWS_SECRET_ACCESS_KEY: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
      AWS_ACCOUNT_ID: "${{ secrets.AWS_ACCOUNT_ID }}"
      AWS_ROLE_NAME: "${{ secrets.AWS_ROLE_NAME }}"
      # Azure Secrets
      AZURE_CLIENT_ID: "${{ secrets.AZURE_CLIENT_ID }}"
      AZURE_TENANT_ID: "${{ secrets.AZURE_TENANT_ID }}"
      AZURE_SUBSCRIPTION_ID: "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
      AZURE_STORAGE_ACCOUNT_NAME: "${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }}"
      AZURE_RESOURCE_GROUP_NAME: "${{ secrets.AZURE_RESOURCE_GROUP_NAME }}"