name: Renovate
on:
  schedule:
    - cron: '25 */5 * * *'

permissions:
  checks: write
  statuses: write
  contents: write
  issues: write
  pull-requests: write
  security-events: read

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v40.2.2
        with:
          configurationFile: ./.github/renovate-global-config.json
          token: ${{ secrets.GITHUB_TOKEN }}
