on:
  pull_request:
    branches:
      - main

jobs:
  tf_apply:
    name: Plan and Apply Terraform Code
    uses: UKHSA-Internal/devops-github-reusable-workflows/.github/workflows/terraform-plan-apply.yml@main
    permissions:
      packages: read
      contents: read
      security-events: write
      statuses: write
      checks: write
    with:
      environment_name: dev
    secrets:
      AWS_ACCESS_KEY_ID: foo
      AWS_SECRET_ACCESS_KEY: bar
      AWS_ACCOUNT_ID: 1234567890
      AWS_ROLE_NAME: ci-deployer-role
