on:
  pull_request:
    branches:
      - main

jobs:
  tf_check:
    name: Check Terraform Code
    uses: UKHSA-Internal/devops-github-reusable-workflows/.github/workflows/terraform-code-check.yml@main
    permissions:
      packages: read
      contents: read
      security-events: write
      statuses: write
      checks: write
